# Web & UI Caching
spring.web.resources.chain.cache=false
gg.jte.developmentMode=true
gg.jte.trimControlStructures=false
gg.jte.usePrecompiledTemplates=false
spring.devtools.livereload.enabled=true

# Database adjustments for Dev
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Logging Levels
sentry.environment=dev


spring.data.redis.host=127.0.0.1
spring.data.redis.password=

