# Base Spring
spring.application.name=formbox
spring.main.lazy-initialization=true
spring.threads.virtual.enabled=true
spring.web.error.whitelabel.enabled=false
gg.jte.templateLocation=src/main/jte

# Cache
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=250,expireAfterAccess=1h
spring.data.redis.port=6379

# PostgreSQL
spring.datasource.url=${FORM_DB_URL}
spring.datasource.username=${FORM_DB_USER}
spring.datasource.password=${FORM_DB_PASS}
spring.datasource.hikari.maximum-pool-size=5
spring.jpa.open-in-view=true

# Monitoring & Logging (Sentry Base)
sentry.dsn=${SENTRY_DSN}
sentry.in-app-includes=formbox
sentry.logging.minimum-breadcrumb-level=debug
sentry.profile-lifecycle=TRACE
sentry.logging.minimum-level=debug
sentry.logging.minimum-event-level=warn
logging.level.formbox=debug
otel.propagators=tracecontext,baggage

otel.traces.exporter=none
otel.metrics.exporter=none
otel.logs.exporter=none

# self-hosted s3 using garage
s3.access-key-id=${S3_ACCESS_KEY_ID}
s3.access-key-secret=${S3_ACCESS_KEY_SECRET}
s3.endpoint-url=https://s3.hridaykh.in
s3.region-name=hyd1a
s3.attachments-bucket=default-bucket
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-request-size=1000MB
spring.servlet.multipart.max-file-size=1000MB

# Third-Party Integrations
auth.supabase-url=${SUPABASE_URL}
auth.supabase-secret-key=${SUPABASE_SECRET_KEY}
auth.turnstile-secret-key=${TURNSTILE_SECRET_KEY}

spring.task.scheduling.pool.size=5
spring.task.scheduling.thread-name-prefix=scheduler-

sentry.traces-sample-rate=1.0
sentry.profile-session-sample-rate=1.0
sentry.logs.enabled=true
sentry.logging.enabled=true

polar.api-url=https://sandbox-api.polar.sh/v1
polar.access-token=${POLAR_API_KEY_DEV}
polar.webhook-secret=${POLAR_WEBHOOK_DEV}
polar-ids.submission-meter-id=${POLAR_SUBMISSION_METER_ID_DEV}

zoho.email.api-url=https://api.zeptomail.in/v1.1/email
zoho.email.api-key=${ZOHO_KEY}
zoho.email.from-address=@notifs.formbox.hridaykh.in
zoho.email.webhook-auth-key=${ZOHO_WEBHOOK}

hmac.key=${HMAC}

