# Web & UI Caching
spring.thymeleaf.cache=true
spring.web.resources.chain.cache=true

# Database security for Prod
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# Logging Levels
logging.level.in.hridaykh.formbox=info
sentry.environment=prod
sentry.logging.minimum-level=info
sentry.logging.minimum-event-level=error
sentry.traces-sample-rate=0.2
sentry.profile-session-sample-rate=0.1

# Third-Party Production Keys
polar.api-url=https://api.polar.sh/v1
polar.access-token=${POLAR_API_KEY_DEV}
polar.webhook-secret=${POLAR_WEBHOOK_SECRET_DEV}
polar-ids.submission-meter-id=${POLAR_SUBMISSION_METER_ID_DEV}
