# Web & UI Caching
spring.thymeleaf.cache=false
spring.web.resources.chain.cache=false

# Database adjustments for Dev
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Logging Levels
logging.level.in.hridaykh.formbox=debug
sentry.environment=dev
sentry.logging.minimum-level=debug
sentry.logging.minimum-event-level=warn
sentry.traces-sample-rate=1.0
sentry.profile-session-sample-rate=1.0
sentry.logs.enabled=false
sentry.logging.enabled=false

# Polar
polar.api-url=https://sandbox-api.polar.sh/v1
polar.access-token=${POLAR_API_KEY_DEV}
polar.webhook-secret=${POLAR_WEBHOOK_DEV}
polar-ids.submission-meter-id=${POLAR_SUBMISSION_METER_ID_DEV}