# ===================================================================
# Spring Application & Server Configuration
# ===================================================================
spring.application.name=formbox
spring.main.lazy-initialization=true
spring.threads.virtual.enabled=true
server.address=0.0.0.0
server.port=${FORMBOX_PORT}
#
#
#
# ===================================================================
# Web & View Layer
# ===================================================================
#
# Thymeleaf
spring.thymeleaf.cache=true
#
# Web Resources & Error Handling
spring.web.resources.chain.cache=true
spring.web.error.whitelabel.enabled=false
#
#
#
# ===================================================================
# Database & Cache (Datasource, JPA, Redis)
# ===================================================================
#
# Datasource
spring.datasource.url=${FORM_DB_URL}
spring.datasource.username=${FORM_DB_USER}
spring.datasource.password=${FORM_DB_PASS}
#
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=true
spring.jpa.show-sql=false
#
# Redis
redis.host=redis.hridaykh.in
redis.port=6379
redis.password=${REDIS_PASS}
#
#
#
# ===================================================================
# Third-Party Integrations
# ===================================================================
#
# Supabase
supabase.url=${SUPABASE_URL}
supabase.publishable-key=${SUPABASE_PUBLISHABLE_KEY}
supabase.secret-key=${SUPABASE_SECRET_KEY}
supabase.jwks-url=${SUPABASE_JWKS_URL}
#
# Resend
resend.api-key=${RESEND_API_KEY}
#
# Polar Configuration
polar.access-token=${POLAR_API_KEY_DEV}
polar.api-url=https://sandbox-api.polar.sh/v1
polar.webhook-secret=${POLAR_WEBHOOK_DEV}
#
# Polar IDs
polar-ids.submission-meter-id=${POLAR_SUBMISSION_METER_ID_DEV}
