# Web & UI Caching
spring.web.resources.chain.cache=true
gg.jte.developmentMode=false
gg.jte.trimControlStructures=true
gg.jte.usePrecompiledTemplates=true

# Database security for Prod
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# Logging Levels
sentry.environment=prod


spring.data.redis.host=${REDIS_IP_PROD}
spring.data.redis.password=${REDIS_PASS}

