# Base Spring
spring.application.name=formbox
spring.main.lazy-initialization=true
spring.threads.virtual.enabled=true
spring.web.error.whitelabel.enabled=false

# Cache
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=1000

# PostgreSQL
spring.datasource.url=${FORM_DB_URL}
spring.datasource.username=${FORM_DB_USER}
spring.datasource.password=${FORM_DB_PASS}
spring.datasource.hikari.maximum-pool-size=5
spring.jpa.open-in-view=true

# Redis
spring.data.redis.host=redis.hridaykh.in
spring.data.redis.port=6379
spring.data.redis.password=${REDIS_PASS}

# Monitoring & Logging (Sentry Base)
sentry.dsn=${SENTRY_DSN}
sentry.in-app-includes=in.hridaykh.formbox
sentry.logging.minimum-breadcrumb-level=debug
sentry.profile-lifecycle=TRACE
sentry.logging.minimum-level=debug
sentry.logging.minimum-event-level=warn
logging.level.in.hridaykh.formbox=debug
otel.propagators=tracecontext,baggage,sentry

otel.traces.exporter=none
otel.metrics.exporter=none
otel.logs.exporter=none

# Third-Party Integrations
supabase.url=${SUPABASE_URL}
supabase.secret-key=${SUPABASE_SECRET_KEY}
