package formbox.notifs;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * Top-level response body returned by ZeptoMail on a successful
 * (2xx) call to POST /v1.1/email.
 *
 * Example:
 * {
 *   "data": [
 *     {
 *       "code": "EM_104",
 *       "additional_info": [],
 *       "message": "OK"
 *     }
 *   ],
 *   "message": "OK",
 *   "request_id": "2233519000000965129",
 *   "object": "email"
 * }
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class ZeptoMailSuccessResponse {

	/** Array of result entries; typically contains a single element. */
	@JsonProperty("data")
	private List<ZeptoMailResponseData> data;

	/** Overall status message for the request, e.g. "OK". */
	@JsonProperty("message")
	private String message;

	/** Unique id generated by ZeptoMail for this request. */
	@JsonProperty("request_id")
	private String requestId;

	/** Signifies which API the response belongs to, e.g. "email". */
	@JsonProperty("object")
	private String object;
}