package formbox.notifs;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class ZeptoMailSuccessResponse {

	/** Array of result entries; typically contains a single element. */
	@JsonProperty("data")
	private List<ZeptoMailResponseData> data;

	/** Overall status message for the request, e.g. "OK". */
	@JsonProperty("message")
	private String message;

	/** Unique id generated by ZeptoMail for this request. */
	@JsonProperty("request_id")
	private String requestId;

	/** Signifies which API the response belongs to, e.g. "autoresponder". */
	@JsonProperty("object")
	private String object;
}