package formbox.notifs.internal.zeptomail;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Top-level response body returned by ZeptoMail on a failed
 * (4xx/5xx) call to POST /v1.1/email.
 *
 * Example:
 * {
 *   "error": {
 *     "code": "TM_3201",
 *     "details": [
 *       {
 *         "code": "TM_3301",
 *         "message": "Invalid data",
 *         "target": "email"
 *       }
 *     ],
 *     "message": "Invalid request"
 *   },
 *   "request_id": "1421357000000965128"
 * }
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class ZeptoMailErrorResponse {

	@JsonProperty("error")
	private ZeptoMailError error;

	/** Unique id generated by ZeptoMail for this request. */
	@JsonProperty("request_id")
	private String requestId;
}